name: Isolate secret in run
on: workflow_dispatch
permissions: {contents: write}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ secrets.RELEASE_KEYSTORE_BASE64 }}" | base64 -d > /tmp/test.p12
          wc -c /tmp/test.p12
