name: Isolate secret dummy
on: workflow_dispatch
permissions: {contents: write}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "test"
        env:
          TEST: "hello world"
