name: Isolate secret raw
on: workflow_dispatch
permissions: {contents: write}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "test"
        env:
          TEST: ${{ secrets.RELEASE_KEYSTORE_BASE64 }}
